### ISSUE TITLE
Windows Docker - bind source path does not exist: /etc/letsencrypt

### ISSUE THREAD

**Issue by VegethB** [nickyu42/myuri#12]
PS B:\SERVER\DOCKER\myuri-master> docker-compose -f docker-compose.prod.yml up -d
Starting myuri_frontend_build ...
Starting myuri_frontend_build ... done
Creating myuri_nginx          ... error

ERROR: for myuri_nginx  Cannot create container for service nginx: invalid mount config for type "bind": bind source path does not exist: /etc/letsencrypt

ERROR: for nginx  Cannot create container for service nginx: invalid mount config for type "bind": bind source path does not exist: /etc/letsencrypt
ERROR: Encountered errors while bringing up the project.

Development work. localhost:80 send a white homescreen but i can't view login admin or anything to do for startup library

**Comment by nickyu42** [comment]
The `/etc/letsencrypt` path does not exist by default.
Currently the production compose file is setup to use TLS certificates from Letsencrypt, which would be setup by the user. It isn't stated in the README, which will be fixed.

Either you can run the project in the development environment (`docker-compose up -d`) or if you really want to configure TLS, you can for example, follow instructions [here](https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) 

This project is very much still in development and does not have an admin page yet nor a comic browser. Meaning it doesn't do anything at the moment. But feel free to follow the project :smiley:

**Comment by VegethB** [comment]
ok, thanks.
